### ISSUE TITLE
Feature request. Implement session history of executed queries

### ISSUE THREAD

**Issue by padlyuck** [noahgorstein/jqp#11]
I think it would be very helpful for users like me, who are not familiar with jq syntax and do many tries and experiments searching for solving their issues.
It would be great if I can select a previously executed query from the dropdown and have the ability to edit it and execute it again.

**Comment by noahgorstein** [comment]
I do really like this suggestion and appreciate it. I think something more in line with what I could do more short-term is saving the session history of executed queries and allowing the user to use `up` key to navigate through, similar to how you'd navigate your shell history.

**Comment by noahgorstein** [comment]
@padlyuck , we had a nice contribution from @nerg4l implementing a basic session history. I haven't cut an official release yet, but feel free to checkout the latest code on `main` and give it a shot.

**Comment by noahgorstein** [comment]
closing this issue. Added in v0.4.0
