### ISSUE TITLE
Support for jsonl

### ISSUE THREAD

**Issue by SamuelLarkin** [noahgorstein/jqp#2]
Hi,
  It would make `jqp` more convenient if it could handle jsonl file aka one json per line.

**Comment by noahgorstein** [comment]
Totally agree here. Would like to add support for this in the future. Appreciate the suggestion.

**Comment by dufferzafar** [comment]
Another similar tool written in Go does have this: https://github.com/gpanders/ijq

**Comment by noahgorstein** [comment]
Completed in #55 - should be in next release! Could also build from source right now and start using if you like.

**Comment by goyalyashpal** [comment]
just for collecting related info/discussion at single place:

> What you describe is NDJSON (New Line Delimited JSON) is 😁, also known as streamed JSON
> [ndjson/ndjson-spec](https://github.com/ndjson/ndjson-spec)
>
> \- @ ccoVeille _at https://github.com/noahgorstein/jqp/issues/54#issuecomment-2047188135_
