### ISSUE TITLE
Slight inconsistency in documented config file path

### ISSUE THREAD

**Issue by ktprograms** [noahgorstein/jqp#24]
[Here](https://github.com/noahgorstein/jqp/blob/f3445e3a1def5c942a0b9a17cadbc08e4e776739/cmd/root.go#L93) it says `".jqp" (without extension)`, but [in the help](https://github.com/noahgorstein/jqp/blob/f3445e3a1def5c942a0b9a17cadbc08e4e776739/cmd/root.go#L127) it says `.jqp.yaml`

**Comment by noahgorstein** [comment]
@ktprograms Apologies of the misleading comment. Most likely just leftover from my implementation when I was wiring up Viper. My understanding is [`viper.SetConfigName`](https://pkg.go.dev/github.com/spf13/viper#SetConfigName) is supposed to take the name of the config file without the extension. This registers it (I should update the comment there to reflect that). `viper.SetConfigType` specifies we only will read from YAML as opposed to json, env, java properties, etc. I'll fix the comment there before cutting a v0.3.0 hopefully sometime this weekend.

**Comment by noahgorstein** [comment]
Fixed the comment in the code.
