### ISSUE TITLE
Copy query to clipboard

### ISSUE THREAD

**Issue by nicolas-martin** [noahgorstein/jqp#28]
It would be really useful to be able to copy the query to clipboard so that I can share the query with others. At the moment, I can't highlight the query and tmux select doesn't work either.

**Comment by noahgorstein** [comment]
@nicolas-martin, this functionality was added in v0.2.0 of `jqp`. Want to give that a shot and see if it works for you?

**Comment by nicolas-martin** [comment]
Yes that works perfectly, thank you!
