### ISSUE TITLE
Debian based release candidate

### ISSUE THREAD

**Issue by Shahin-rmz** [noahgorstein/jqp#45]
Hello, 
The project makes life so much easier, thanks.
I just want to know if for Ubuntu/Debian Distros should we only `make` the jqp or it is also possible to install it via package managers?
Best

**Comment by noahgorstein** [comment]
Hey @Shahin-rmz. Thanks for the kind words. 

Not sure exactly what you mean. Are you trying to create packages for Ubuntu and Debian? To my knowledge, they don't exist right now.
