### ISSUE TITLE
output not prettyprinted

### ISSUE THREAD

**Issue by octoshrimpy** [noahgorstein/jqp#52]
makes it rather difficult to parse. installed from AUR, v0.5.0

![image](https://github.com/noahgorstein/jqp/assets/7097172/553e48d2-5bab-4a95-9cd9-70ae8beb3b88)

**Comment by noahgorstein** [comment]
Yeah I guess in this case the output is not technically JSON so it fails to format it. It's JSON lines (JSONL) if I'm recalling correctly. Perhaps we can make enhancement to attempt to format each JSON line though. Will consider it!

**Comment by noahgorstein** [comment]
Completed in #55 !
