### ISSUE TITLE
Wrong Selecton Border

### ISSUE THREAD

**Issue by bigshans** [noahgorstein/jqp#6]
![图片](https://user-images.githubusercontent.com/26884666/191450515-6a49b8b9-4b2e-4213-81bf-fcb9a9691aa3.png)

**Comment by noahgorstein** [comment]
Hi @bigshans, thanks for your report. Could you share some steps of how you got into that state? Additionally, can you share what terminal emulator application you're using and your OS?

**Comment by bigshans** [comment]
> Hi @bigshans, thanks for your report. Could you share some steps of how you got into that state? Additionally, can you share what terminal emulator application you're using and your OS?

1. run the example `curl "https://api.github.com/repos/stedolan/jq/issues?per_page=2" | jqp` .
2. OS: Arch. Desktop: KDE Plasma 5.25.5.

I tested konsole, kitty, wezterm, xfce terminal and gnome terminal. All can be reproduced.

**Comment by corestate55** [comment]
I had the same issue, but by specifying the `LANG` as follows, I got the correct borderline.
* `LANG=ja_JP.UTF-8 jqp -f foo.json` : wrong border
* `LANG=en_US.UTF-8 jqp -f foo.json` : expected border

I use jqp/0.4.0 on Ubuntu desktopo 22.04, GNOME terminal.
