### ISSUE TITLE
Please consider adding more GitHub actions

### ISSUE THREAD

**Issue by ccoVeille** [noahgorstein/jqp#60]
I'm thinking about

- launching test on PR

- launching golangci-lint on PR

- checking typos (avoid corrective PR  like #59)

- dependabot to make sure dependencies are up to date, but also that github actions are also kept up to date

**Comment by ccoVeille** [comment]
I can help of course

**Comment by ccoVeille** [comment]
I made #62, #63 and #64

**Comment by noahgorstein** [comment]
@ccoVeille Really appreciate all your contributions in this area! The project's health (and myself) thank you 😄 . Think this will make future contributions much easier to review and give us some more confidence when we add some tests that no regressions are being introduced.
