### ISSUE TITLE
Ability to specify query via command line

### ISSUE THREAD

**Issue by greggannicott** [noahgorstein/jqp#65]
It would be useful to be able to specify the query via the command line and have the query input pre-populated with the query, and the results applying the query.

My example use case is that I'm using `jq` to run queries and view them on the command line. It would be handy to easily switch to `jqp` to have the results displayed in `jqp` instead.

I realise I could just pipe data through jq before jqp (eg. `jq 'my query' | jqp`) but it would be helpful for the query to be passed in too.

So something like:

```bash
curl "http://mydomain.com" | jqp 'my query'
```

Thanks.

**Comment by noahgorstein** [comment]
Sure thing. Great suggestion. Should be a fairly straightforward addition.

**Comment by noahgorstein** [comment]
Should be in next release !

**Comment by noahgorstein** [comment]
this is now officially released in v0.7.0
