### ISSUE TITLE
Cursor jumps to the end of line after typing one character at the beginning of query

### ISSUE THREAD

**Issue by padlyuck** [noahgorstein/jqp#9]
Steps to reproduce:
Type just a simple query `.`
Press Ctrl+a to jump to the beginning
Try to type `map`

**Comment by noahgorstein** [comment]
Hey thanks for reporting this issue @padlyuck. Think this may be an issue with an upstream dependency and will see if I can work around it.

**Comment by noahgorstein** [comment]
@padlyuck Confirmed this is an issue with the dependency on Bubbles. Already resolved in their `master` branch and should be included in their next release iiuc. If you want to build `jqp` locally, you can get a version with this issue fixed by first running:

```bash
go get github.com/charmbracelet/bubbles@master
```

**Comment by padlyuck** [comment]
Thanks for your work! I'll wait for the next release of jpq! It helps me in my work a lot.
